[package]
name = "chat_server"
version = "0.1.0"
authors = ["Glenn Huval <glennh@kinoo.family>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
popol = "0.4.0"
ctrlc = "3.1.0"
bus = "2.2.3"